---
abstract: 'Perl extension for using OpenSSL'
author:
  - 'Maintained by Mike McCauley and Florian Ragwitz since November 2005'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SSLeay
no_index:
  directory:
    - inc
    - ext
    - inc
    - t
    - examples
requires:
  MIME::Base64: 0
version: 1.35
